services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KimaiPlugin\PersonalCalendarPrefBundle\:
        resource: '../../*'
        exclude: '../../{Resources}'
